import 'package:flutter/material.dart';

import 'theme_library.dart';

class AppTheme {
  AppTheme._();

  factory AppTheme() {
    return instance;
  }

  static final AppTheme instance = AppTheme._();

  ThemeData get light {
    return ThemeData(
        useMaterial3: true,
        brightness: Brightness.light,
        colorScheme: colorSchemeLight,
        iconTheme: iconThemeData,
        appBarTheme: appBarTheme,
        // textTheme: darkTxtTheme,
        // primaryTextTheme: darkTxtTheme,
        bottomNavigationBarTheme: bottomNavigationBarTheme,
        bannerTheme: bannerTheme,
        bottomAppBarTheme: bottomAppBarTheme,
        bottomSheetTheme: bottomSheetTheme,
        // buttonBarTheme: buttonBarTheme,
        buttonTheme: buttonTheme,
        shadowColor: colorSchemeLight.shadow,
        canvasColor: colorSchemeLight.surface,
        cardTheme: cardTheme,
        checkboxTheme: checkboxTheme,
        chipTheme: chipThemeData,
        dataTableTheme: dataTableTheme,
        datePickerTheme: datePickerTheme,
        dialogTheme: dialogTheme,
        dividerTheme: dividerTheme,
        drawerTheme: drawerTheme,
        elevatedButtonTheme: elevatedButtonTheme,
        expansionTileTheme: expansionTileTheme,
        inputDecorationTheme: inputDecorationTheme,
        filledButtonTheme: filledButtonTheme,
        iconButtonTheme: iconButtonTheme,
        outlinedButtonTheme: outlinedButtonTheme,
        radioTheme: radioThemeData,
        textButtonTheme: textButtonTheme,
        switchTheme: switchTheme,
        toggleButtonsTheme: toggleButtonsTheme,
        tooltipTheme: tooltipTheme,
        timePickerTheme: timePickerTheme,
        tabBarTheme: tabBarTheme,
        snackBarTheme: snackBarTheme,
        segmentedButtonTheme: segmentedButtonTheme,
        listTileTheme: listTileTheme,
        menuButtonTheme: menuButtonTheme,
        sliderTheme: sliderTheme,
        menuTheme: menuTheme,
        menuBarTheme: menuBarTheme,
        floatingActionButtonTheme: floatingActionButtonTheme,
        navigationBarTheme: navigationBarTheme,
        navigationRailTheme: navigationRailTheme,
        pageTransitionsTheme: pageTransitionsTheme,
        popupMenuTheme: popupMenuTheme,
        scrollbarTheme: scrollbarTheme,
        searchBarTheme: searchBarTheme,
        searchViewTheme: searchViewTheme,
        progressIndicatorTheme: progressIndicatorTheme,
        splashFactory: InkRipple.splashFactory,
        textSelectionTheme: textSelectionTheme,
        navigationDrawerTheme: navigationDrawerTheme,
        focusColor: colorSchemeLight.primary,
        typography: typography,
        dropdownMenuTheme: dropdownMenuTheme,
        primarySwatch: primaryMaterial,
        cardColor: colorSchemeLight.surface,
        dialogBackgroundColor: colorSchemeLight.surface,
        disabledColor: colorSchemeLight.onSurface.withOpacity(0.38),
        dividerColor: colorSchemeLight.outline,
        highlightColor: colorSchemeLight.primaryContainer,
        hintColor: colorSchemeLight.onSurfaceVariant,
        hoverColor: colorSchemeLight.secondaryContainer.withOpacity(0.08),
        primaryColor: colorSchemeLight.primary,
        primaryColorDark: colorSchemeLight.primaryContainer,
        primaryColorLight: colorSchemeLight.primaryContainer,
        secondaryHeaderColor: colorSchemeLight.secondaryContainer,
        splashColor: colorSchemeLight.secondaryContainer.withOpacity(0.12),
        materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
        primaryIconTheme: primaryIconTheme,
        indicatorColor: colorSchemeLight.secondary,
        unselectedWidgetColor: colorSchemeLight.onSurface.withOpacity(0.60),
        visualDensity: VisualDensity.adaptivePlatformDensity,
        applyElevationOverlayColor: false,
        scaffoldBackgroundColor: colorSchemeLight.surface);
  }

// ThemeData get dark {
//   return ThemeData(
//       useMaterial3: true,
//       brightness: Brightness.dark,
//       colorScheme: colorSchemeDark,
//       appBarTheme: darkAppBarTheme,
//       iconTheme: darkIconThemeData,
//       // textTheme: darkTxtTheme,
//       // primaryTextTheme: darkTxtTheme,
//       bottomNavigationBarTheme: darkBottomNavigationBarTheme,
//       bannerTheme: darkBannerTheme,
//       bottomAppBarTheme: darkBottomAppBarTheme,
//       bottomSheetTheme: darkBottomSheetTheme,
//       // buttonBarTheme: darkButtonBarTheme,
//       buttonTheme: darkButtonTheme,
//       shadowColor: colorSchemeDark.shadow,
//       canvasColor: colorSchemeDark.surface,
//       cardTheme: darkCardTheme,
//       checkboxTheme: darkCheckboxTheme,
//       chipTheme: darkChipThemeData,
//       dataTableTheme: darkDataTableTheme,
//       datePickerTheme: darkDatePickerTheme,
//       dialogTheme: darkDialogTheme,
//       dividerTheme: darkDividerTheme,
//       drawerTheme: darkDrawerTheme,
//       elevatedButtonTheme: darkElevatedButtonTheme,
//       expansionTileTheme: darkExpansionTileTheme,
//       inputDecorationTheme: darkInputDecorationTheme,
//       filledButtonTheme: darkFilledButtonTheme,
//       iconButtonTheme: darkIconButtonTheme,
//       outlinedButtonTheme: darkOutlinedButtonTheme,
//       radioTheme: darkRadioThemeData,
//       textButtonTheme: darkTextButtonTheme,
//       switchTheme: darkSwitchTheme,
//       toggleButtonsTheme: darkToggleButtonsTheme,
//       tooltipTheme: darkTooltipTheme,
//       timePickerTheme: darkTimePickerTheme,
//       tabBarTheme: darkTabBarTheme,
//       snackBarTheme: darkSnackBarTheme,
//       segmentedButtonTheme: darkSegmentedButtonTheme,
//       listTileTheme: darkListTileTheme,
//       menuButtonTheme: darkMenuButtonTheme,
//       sliderTheme: darkSliderTheme,
//       menuTheme: darkMenuTheme,
//       menuBarTheme: darkMenuBarTheme,
//       floatingActionButtonTheme: darkFloatingActionButtonTheme,
//       navigationBarTheme: darkNavigationBarTheme,
//       navigationRailTheme: darkNavigationRailTheme,
//       pageTransitionsTheme: darkPageTransitionsTheme,
//       popupMenuTheme: darkPopupMenuTheme,
//       scrollbarTheme: darkScrollbarTheme,
//       searchBarTheme: darkSearchBarTheme,
//       searchViewTheme: darkSearchViewTheme,
//       progressIndicatorTheme: darkProgressIndicatorTheme,
//       splashFactory: InkRipple.splashFactory,
//       textSelectionTheme: darkTextSelectionTheme,
//       navigationDrawerTheme: darkNavigationDrawerTheme,
//       focusColor: colorSchemeDark.primary,
//       typography: darkTypography,
//       dropdownMenuTheme: darkDropdownMenuTheme,
//       primarySwatch: darkPrimaryMaterial,
//       cardColor: colorSchemeDark.surface,
//       dialogBackgroundColor: colorSchemeDark.surface,
//       disabledColor: colorSchemeDark.onSurface.withOpacity(0.38),
//       dividerColor: colorSchemeDark.outline,
//       highlightColor: colorSchemeDark.primaryContainer,
//       hintColor: colorSchemeDark.onSurfaceVariant,
//       hoverColor: colorSchemeDark.secondaryContainer.withOpacity(0.08),
//       primaryColor: colorSchemeDark.primary,
//       primaryColorDark: colorSchemeDark.primaryContainer,
//       primaryColorLight: colorSchemeDark.primaryContainer,
//       secondaryHeaderColor: colorSchemeDark.secondaryContainer,
//       splashColor: colorSchemeDark.secondaryContainer.withOpacity(0.12),
//       materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
//       primaryIconTheme: darkPrimaryIconTheme,
//       indicatorColor: colorSchemeDark.secondary,
//       unselectedWidgetColor: colorSchemeDark.onSurface.withOpacity(0.60),
//       visualDensity: VisualDensity.adaptivePlatformDensity,
//       applyElevationOverlayColor: false,
//       scaffoldBackgroundColor: colorSchemeDark.surface);
// }
}
